services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: shaula
      POSTGRES_USER: shaula
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./services/DB/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
  
  datafeed:
    build:
      context: ./services/DataFeed
      dockerfile: Dockerfile
    container_name: datafeed
    ports:
      - "3047:3047"
    depends_on:
      - postgres

  strat:
    build:
      context: ./services/Strat
      dockerfile: Dockerfile
    container_name: strat
    ports:
      - "3048:3048"
    depends_on:
      - postgres
      - datafeed

volumes:
  postgres_data: